improve: order of nested test
dry-rb/dry-validation pull request #695
Opened 2021-12-04 17:25 UTC by JuanVqz

2021-12-06 10:23 UTC, solnic commented
Thanks but what is exactly improved here?

2021-12-06 14:01 UTC, JuanVqz commented
I was extracting the following block code in a `before each` I thought it may be an improvement.

```ruby
      contract_class.rule(:tags) do
        key.failure("must have at least 1 element") unless value.size > 0
      end
```

2021-12-07 08:41 UTC, solnic requested changes

2021-12-07 08:41 UTC, solnic commented on spec/unit/rule_spec.rb
> +    before :each do
```suggestion
    before do
```

2022-03-16 12:58 UTC, closed without merging